// Approach 5 — Compile-time DI (Google Wire style) — wiring entry point
//
// This file contains the App bootstrapper and the main function.
// InitApp() lives in wire_gen.go (simulated generated code).
//
// See README.md for the Wire workflow, provider graph, and when to use.
//
// Run: go run ./cmd/05_wire_di/
package main

import (
	"context"
	"net/http"
	"os"
	"os/signal"
	"syscall"

	"github.com/example/di_in_go/internal/adapters/rest"
)

// App bundles the HTTP server and the logger needed to drive startup/shutdown.
// Wire builds this struct by resolving the full dependency graph transitively.
type App struct {
	srv *http.Server
}

func NewApp(h *rest.UserHandler) *App {
	mux := http.NewServeMux()
	mux.HandleFunc("POST /users", h.Create)
	mux.HandleFunc("GET /users/{id}", h.Get)

	return &App{
		srv: &http.Server{
			Addr:    ":8084",
			Handler: rest.Chain(mux, rest.RequestIDMiddleware),
		},
	}
}

func main() {
	// InitApp() is generated by the Wire CLI into wire_gen.go.
	// You run `wire ./cmd/05_wire_di/` once; after that the file is committed.
	app := InitApp()

	go func() {
		if err := app.srv.ListenAndServe(); err != nil && err != http.ErrServerClosed {
			os.Exit(1)
		}
	}()

	quit := make(chan os.Signal, 1)
	signal.Notify(quit, syscall.SIGINT, syscall.SIGTERM)
	<-quit
	app.srv.Shutdown(context.Background())
}
