// Code generated by Wire. DO NOT EDIT.
//
//go:generate wire
//go:build !wireinject

package main

import (
	"github.com/example/di_in_go/internal/adapters/repository"
	"github.com/example/di_in_go/internal/adapters/rest"
	"github.com/example/di_in_go/internal/application"
	infradb "github.com/example/di_in_go/internal/infrastructure/db"
	"github.com/example/di_in_go/internal/infrastructure/email"
	"github.com/example/di_in_go/internal/infrastructure/logger"
	"github.com/example/di_in_go/internal/infrastructure/validator"
)

// InitApp wires the full dependency graph.
//
// Wire emits this function by topologically sorting the provider graph defined
// in providers.go.  Each constructor is called exactly once → all objects are
// Singletons within one InitApp() invocation.
//
// If a dependency is missing or a type mismatch exists, the wire CLI reports
// it as a compile-time error — not a runtime panic.
func InitApp() *App {
	// ── Singletons — one allocation each, order determined by Wire ──
	log := logger.New()                   // ProvideLogger()
	db := infradb.New()                   // ProvideDB()
	val := validator.New()                // ProvideValidator()
	emailSvc := email.NewStub(log)        // ProvideEmailService(log)
	repo := repository.NewMemory(db, log) // (repo provider)
	svc := application.NewUserService(    // ProvideUserService(...)
		repo, emailSvc, val, log,
	)
	h := rest.NewUserHandler(svc, log) // ProvideUserHandler(svc, log)
	return NewApp(h)                   // ProvideApp(h)
}
